services:
  backend:
    build: ./backend
    command: npm run start:dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - "/app/node_modules"
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: ./backend/src
          ignore:
            - node_modules/
        - action: rebuild
          path: backend/package.json

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: ./frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: frontend/package.json
