# fly.toml app configuration file generated for <app-name> on 2024-08-06T10:24:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'supply-chain-ms-be'
primary_region = 'jnb'

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3_000
  min_machines_running = 0
  processes = [ "app" ]

[[vm]]
  cpu_kind = 'shared'
  memory = '1gb'
  cpus = 1
  memory_mb = 1_024
