// This file is auto-generated by @hey-api/openapi-ts

export const BaseResponseDtoSchema = {
  type: "object",
  properties: {
    data: {
      type: "object",
    },
    message: {
      type: "string",
      example: "Success",
    },
    status: {
      type: "boolean",
      example: true,
    },
  },
} as const;

export const LoginResponseDtoSchema = {
  type: "object",
  properties: {
    access_token: {
      type: "string",
      example: "eyJhbGic...",
    },
  },
} as const;

export const LoginRequestDtoSchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
      description: "email",
    },
    password: {
      type: "string",
      description: "password",
    },
  },
  required: ["email", "password"],
} as const;

export const UserResponseDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "object",
      example: "id-here",
    },
    first_name: {
      type: "object",
      example: "Firstname",
    },
    last_name: {
      type: "object",
      example: "Lastname",
    },
    email: {
      type: "object",
      example: "user@mail.com",
    },
    account_status: {
      type: "string",
      example: "ACTIVE",
    },
    role: {
      type: "string",
      example: "SHIPPER",
    },
    created_at: {
      type: "object",
      example: "2025-06-05 06:55:28.677072+01",
    },
  },
} as const;

export const RegistrationRequestDtoSchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
      description: "email",
    },
    password: {
      type: "string",
      description: "password",
    },
    repeat_password: {
      type: "string",
      description: "Repeat password",
    },
    first_name: {
      type: "string",
      description: "first_name",
    },
    last_name: {
      type: "string",
      description: "last_name",
    },
    role: {
      type: "string",
      enum: ["PLATFORM_ADMIN", "SHIPPER", "VENDOR"],
      description: "Role must be one of PLATFORM_ADMIN",
    },
  },
  required: [
    "email",
    "password",
    "repeat_password",
    "first_name",
    "last_name",
    "role",
  ],
} as const;

export const PaginationMetaDtoSchema = {
  type: "object",
  properties: {
    totalItems: {
      type: "number",
    },
    itemCount: {
      type: "number",
    },
    itemsPerPage: {
      type: "number",
    },
    totalPages: {
      type: "number",
    },
    currentPage: {
      type: "number",
    },
  },
  required: [
    "totalItems",
    "itemCount",
    "itemsPerPage",
    "totalPages",
    "currentPage",
  ],
} as const;

export const PaginatedResponseDtoSchema = {
  type: "object",
  properties: {
    data: {
      type: "array",
      items: {
        type: "array",
      },
    },
    meta: {
      $ref: "#/components/schemas/PaginationMetaDto",
    },
  },
  required: ["data", "meta"],
} as const;

export const QuoteRequestResponseDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      description: "id",
    },
    qr_num: {
      type: "string",
      description: "qr_num",
    },
    origin_address: {
      type: "string",
      description: "origin_address",
    },
    destination_address: {
      type: "string",
      description: "destination_address",
    },
    distance_km: {
      type: "number",
      description: "distance_km",
    },
    weight_kg: {
      type: "number",
      description: "weight_kg",
    },
    goods_type: {
      type: "string",
      description: "goods_type",
    },
    additional_note: {
      type: "string",
      description: "additional_note",
    },
    urgency: {
      type: "string",
      description: "urgency",
      default: "STANDARD",
    },
    status: {
      type: "string",
      description: "status",
    },
    created_at: {
      type: "object",
      example: "2025-06-05 06:55:28.677072+01",
    },
    user: {
      description: "user",
      allOf: [
        {
          $ref: "#/components/schemas/UserResponseDto",
        },
      ],
    },
    vendor: {
      description: "vendor",
      allOf: [
        {
          $ref: "#/components/schemas/UserResponseDto",
        },
      ],
    },
  },
  required: [
    "id",
    "qr_num",
    "origin_address",
    "destination_address",
    "distance_km",
    "weight_kg",
    "goods_type",
    "additional_note",
    "urgency",
    "status",
    "user",
    "vendor",
  ],
} as const;

export const CreateRequestQuoteRequestDtoSchema = {
  type: "object",
  properties: {
    vendor_id: {
      type: "string",
      description: "vendor_id",
    },
    origin_address: {
      type: "string",
      description: "origin_address",
    },
    destination_address: {
      type: "string",
      description: "destination_address",
    },
    distance_km: {
      type: "number",
      description: "distance_km",
    },
    weight_kg: {
      type: "number",
      description: "weight_kg",
    },
    goods_type: {
      type: "string",
      description: "goods_type",
    },
    additional_note: {
      type: "string",
      description: "additional_note",
    },
    urgency: {
      type: "string",
      description: "urgency",
      default: "STANDARD",
    },
  },
  required: [
    "vendor_id",
    "origin_address",
    "destination_address",
    "distance_km",
    "weight_kg",
    "goods_type",
    "additional_note",
    "urgency",
  ],
} as const;
