// This file is auto-generated by @hey-api/openapi-ts

export type BaseResponseDto = {
  data?: {
    [key: string]: unknown;
  };
  message?: string;
  status?: boolean;
};

export type LoginResponseDto = {
  access_token?: string;
};

export type LoginRequestDto = {
  /**
   * email
   */
  email: string;
  /**
   * password
   */
  password: string;
};

export type UserResponseDto = {
  id?: {
    [key: string]: unknown;
  };
  first_name?: {
    [key: string]: unknown;
  };
  last_name?: {
    [key: string]: unknown;
  };
  email?: {
    [key: string]: unknown;
  };
  account_status?: string;
  role?: string;
  created_at?: {
    [key: string]: unknown;
  };
};

export type RegistrationRequestDto = {
  /**
   * email
   */
  email: string;
  /**
   * password
   */
  password: string;
  /**
   * Repeat password
   */
  repeat_password: string;
  /**
   * first_name
   */
  first_name: string;
  /**
   * last_name
   */
  last_name: string;
  /**
   * Role must be one of PLATFORM_ADMIN
   */
  role: "PLATFORM_ADMIN" | "SHIPPER" | "VENDOR";
};

export type PaginationMetaDto = {
  totalItems: number;
  itemCount: number;
  itemsPerPage: number;
  totalPages: number;
  currentPage: number;
};

export type PaginatedResponseDto = {
  data: Array<Array<unknown>>;
  meta: PaginationMetaDto;
};

export type QuoteRequestResponseDto = {
  /**
   * id
   */
  id: string;
  /**
   * qr_num
   */
  qr_num: string;
  /**
   * origin_address
   */
  origin_address: string;
  /**
   * destination_address
   */
  destination_address: string;
  /**
   * distance_km
   */
  distance_km: number;
  /**
   * weight_kg
   */
  weight_kg: number;
  /**
   * goods_type
   */
  goods_type: string;
  /**
   * additional_note
   */
  additional_note: string;
  /**
   * urgency
   */
  urgency: string;
  /**
   * status
   */
  status: string;
  created_at?: {
    [key: string]: unknown;
  };
  /**
   * user
   */
  user: UserResponseDto;
  /**
   * vendor
   */
  vendor: UserResponseDto;
};

export type CreateRequestQuoteRequestDto = {
  /**
   * vendor_id
   */
  vendor_id: string;
  /**
   * origin_address
   */
  origin_address: string;
  /**
   * destination_address
   */
  destination_address: string;
  /**
   * distance_km
   */
  distance_km: number;
  /**
   * weight_kg
   */
  weight_kg: number;
  /**
   * goods_type
   */
  goods_type: string;
  /**
   * additional_note
   */
  additional_note: string;
  /**
   * urgency
   */
  urgency: string;
};

export type AuthControllerLoginData = {
  body: LoginRequestDto;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type AuthControllerLoginErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type AuthControllerLoginResponses = {
  /**
   * Welcome back
   */
  200: BaseResponseDto & {
    data?: LoginResponseDto;
  };
};

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRegisterData = {
  body: RegistrationRequestDto;
  path?: never;
  query?: never;
  url: "/api/auth/register";
};

export type AuthControllerRegisterErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type AuthControllerRegisterResponses = {
  /**
   * Register user
   */
  200: BaseResponseDto & {
    data?: UserResponseDto;
  };
};

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type UsersControllerGetUserData = {
  body?: never;
  path: {
    /**
     * id
     */
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersControllerGetUserErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Unathorized
   */
  401: unknown;
};

export type UsersControllerGetUserResponses = {
  /**
   * Get user account
   */
  200: BaseResponseDto & {
    data?: UserResponseDto;
  };
};

export type UsersControllerGetUserResponse =
  UsersControllerGetUserResponses[keyof UsersControllerGetUserResponses];

export type AdminUsersControllerGetUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * page
     */
    page?: number;
    /**
     * pageSize
     */
    pageSize?: number;
    /**
     * role
     */
    role?: "PLATFORM_ADMIN" | "SHIPPER" | "VENDOR" | "DRIVER";
    /**
     * accountStatus
     */
    accountStatus?: "ACTIVE" | "SUSPENDED" | "PENDING_VERIFICATION" | "INVITED";
  };
  url: "/api/admin/users";
};

export type AdminUsersControllerGetUsersErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Unathorized
   */
  401: unknown;
};

export type AdminUsersControllerGetUsersResponses = {
  /**
   * Paginated users
   */
  200: PaginatedResponseDto & {
    status?: boolean;
    message?: string;
    data?: Array<UserResponseDto>;
  };
};

export type AdminUsersControllerGetUsersResponse =
  AdminUsersControllerGetUsersResponses[keyof AdminUsersControllerGetUsersResponses];

export type AdminUsersControllerSuspendUserData = {
  body?: never;
  path: {
    /**
     * id
     */
    id: string;
  };
  query?: never;
  url: "/api/admin/users/{id}/suspend";
};

export type AdminUsersControllerSuspendUserErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Unathorized
   */
  401: unknown;
};

export type AdminUsersControllerSuspendUserResponses = {
  /**
   * Suspend user account
   */
  200: BaseResponseDto & {
    data?: UserResponseDto;
  };
};

export type AdminUsersControllerSuspendUserResponse =
  AdminUsersControllerSuspendUserResponses[keyof AdminUsersControllerSuspendUserResponses];

export type AdminUsersControllerActivateUserData = {
  body?: never;
  path: {
    /**
     * id
     */
    id: string;
  };
  query?: never;
  url: "/api/admin/users/{id}/activate";
};

export type AdminUsersControllerActivateUserErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Unathorized
   */
  401: unknown;
};

export type AdminUsersControllerActivateUserResponses = {
  /**
   * Activate user account
   */
  200: BaseResponseDto & {
    data?: UserResponseDto;
  };
};

export type AdminUsersControllerActivateUserResponse =
  AdminUsersControllerActivateUserResponses[keyof AdminUsersControllerActivateUserResponses];

export type ProfileControllerProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/profile";
};

export type ProfileControllerProfileErrors = {
  /**
   * Unathorized
   */
  401: unknown;
};

export type ProfileControllerProfileResponses = {
  /**
   * Current user profile
   */
  200: BaseResponseDto & {
    data?: UserResponseDto;
  };
};

export type ProfileControllerProfileResponse =
  ProfileControllerProfileResponses[keyof ProfileControllerProfileResponses];

export type QuotesControllerAcceptQuoteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/quotes/{id}/accept";
};

export type QuotesControllerAcceptQuoteErrors = {
  /**
   * Unathorized
   */
  401: unknown;
};

export type QuotesControllerRejectQuoteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/quotes/{id}/reject";
};

export type QuotesControllerRejectQuoteErrors = {
  /**
   * Unathorized
   */
  401: unknown;
};

export type QuotesControllerGetQuotesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/quotes";
};

export type QuotesControllerGetQuotesErrors = {
  /**
   * Unathorized
   */
  401: unknown;
};

export type QuotesControllerGetQuoteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/quotes/{id}";
};

export type QuotesControllerGetQuoteErrors = {
  /**
   * Unathorized
   */
  401: unknown;
};

export type QuoteRequestsControllerListRequestedQuotesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * page
     */
    page?: number;
    /**
     * pageSize
     */
    pageSize?: number;
    /**
     * urgency
     */
    urgency?: "STANDARD" | "EXPRESS";
    /**
     * search
     */
    search?: string;
  };
  url: "/api/quotes-requests";
};

export type QuoteRequestsControllerListRequestedQuotesErrors = {
  /**
   * Unathorized
   */
  401: unknown;
};

export type QuoteRequestsControllerListRequestedQuotesResponses = {
  /**
   * quote requests list
   */
  200: PaginatedResponseDto & {
    status?: boolean;
    message?: string;
    data?: Array<QuoteRequestResponseDto>;
  };
};

export type QuoteRequestsControllerListRequestedQuotesResponse =
  QuoteRequestsControllerListRequestedQuotesResponses[keyof QuoteRequestsControllerListRequestedQuotesResponses];

export type QuoteRequestsControllerRequestQuoteData = {
  body: CreateRequestQuoteRequestDto;
  path?: never;
  query?: never;
  url: "/api/quotes-requests";
};

export type QuoteRequestsControllerRequestQuoteErrors = {
  /**
   * Bad request
   */
  400: unknown;
  /**
   * Unathorized
   */
  401: unknown;
};

export type QuoteRequestsControllerRequestQuoteResponses = {
  /**
   * Quote request sent successfully
   */
  200: BaseResponseDto & {
    data?: QuoteRequestResponseDto;
  };
};

export type QuoteRequestsControllerRequestQuoteResponse =
  QuoteRequestsControllerRequestQuoteResponses[keyof QuoteRequestsControllerRequestQuoteResponses];

export type QuoteRequestsControllerRequestQuoteDetailData = {
  body?: never;
  path: {
    /**
     * id
     */
    id: string;
  };
  query?: never;
  url: "/api/quotes-requests/{id}";
};

export type QuoteRequestsControllerRequestQuoteDetailErrors = {
  /**
   * Unathorized
   */
  401: unknown;
  /**
   * Quote request not found
   */
  404: unknown;
};

export type QuoteRequestsControllerRequestQuoteDetailResponses = {
  /**
   * quote request detail
   */
  200: BaseResponseDto & {
    data?: QuoteRequestResponseDto;
  };
};

export type QuoteRequestsControllerRequestQuoteDetailResponse =
  QuoteRequestsControllerRequestQuoteDetailResponses[keyof QuoteRequestsControllerRequestQuoteDetailResponses];

export type QuoteRequestsControllerRespondQuoteRequestData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/quotes-requests/{id}/respond";
};

export type QuoteRequestsControllerRespondQuoteRequestErrors = {
  /**
   * Unathorized
   */
  401: unknown;
};

export type ClientOptions = {
  baseURL: string;
};
