export enum Role {
  // main admins
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  PLATFORM_STAFF = 'PLATFORM_STAFF',
  SUPPORT_STAFF = 'SUPPORT_STAFF',
  // shippers
  SHIPPER_ADMIN = 'SHIPPER_ADMIN',
  SHIPPER_STAFF = 'SHIPPER_STAFF',
  // vendors
  VENDOR_ADMIN = 'VENDOR_ADMIN',
  VENDOR_OPERATOR = 'VENDOR_OPERATOR',
  VENDOR_DRIVER = 'VENDOR_DRIVER',
}
